### ISSUE TITLE
Megaman X2 crashes

### ISSUE THREAD

**Issue by prataczak** [libretro/bsnes-mercury#23]
I tried both the accuracy and balanced cores, both crash. Megaman X3 works fine, and Megaman X2 works fine in regular BSNES accuracy.

**Comment by hizzlekizzle** [comment]
Seems fine here using mercury accuracy and balanced in linux. Where is it supposed to crash?

**Comment by prataczak** [comment]
I'm on the Windows version, sorry I should have specified. It happens as soon as the game is loaded.

**Comment by prataczak** [comment]
Donkey Kong Country 3 crashes also.

**Comment by hizzlekizzle** [comment]
Could you try this build of bsnes-mercury-accuracy (win64)?
http://www.mediafire.com/file/v27gdc95348fzik/bsnes_mercury_accuracy_libretro.dll

**Comment by prataczak** [comment]
Mega Man X2 works with that one, and Donkey Kong Country 3 still crashes when first loading.

**Comment by hizzlekizzle** [comment]
ok, it's probably toolchain issues with the buildbot, then. DKC3 works fine in linux, as well, so that may be a more general mingw issue. Anyway, thanks for testing. We'll look into it.

**Comment by prataczak** [comment]
No problem, thanks for all your hard work.

**Comment by fr500** [comment]
it's a problem with cheevos
maybe @leiradel or @Alcaro can figure it out

> (gdb) bt
#0  cheevos_get_var_value (var=0x690f21c) at cheevos.c:1129
#1  cheevos_test_condition (cond=0x690f210) at cheevos.c:1175
#2  cheevos_test_cond_set (dirty_conds=dirty_conds@entry=0x3fffa5c,
    reset_conds=reset_conds@entry=0x3fffa60, condset=<optimized out>,
    condset=<optimized out>, match_any=0) at cheevos.c:1239
#3  0x0000000000642961 in cheevos_test_cheevo (cheevo=0x134fc8a0)
    at cheevos.c:1320
#4  cheevos_test_cheevo_set (set=<optimized out>, set=<optimized out>)
    at cheevos.c:1484
#5  0x00000000006451d3 in cheevos_test () at cheevos.c:2354
#6  0x0000000000412057 in runloop_iterate (sleep_ms=sleep_ms@entry=0x3fffde0)
    at runloop.c:1370
#7  0x00000000004016c0 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:125
#8  0x0000000000653528 in WinMain ()
#9  0x00000000004013ed in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#10 0x000000000040152b in mainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:212

**Comment by leiradel** [comment]
@fr500 which core and game resulted in that crash?

**Comment by fr500** [comment]
Megaman X2, mercury balanced or accuracy

**Comment by prataczak** [comment]
Donkey Kong Country 3 also crashes.
